### ISSUE TITLE
Scroll in reverse order

### ISSUE THREAD

**Issue by interazioni** [pixelcog/parallax.js#146] opened 2016-05-01 19:52 UTC
I'd love to have the possibility to make scroll in reverse order (compared to actual).
When including HTML content, it may be more opportune to start from top and scroll to bottom, following the natural flow of text, just at different speed.
So, it would be nice to have this specific function, it would complete the package.
Thanks for all work!

**Comment by KaelWD** [comment] 2016-05-03 14:26
Try setting a negative `speed`.

**Comment by interazioni** [comment] 2016-05-03 14:37
I did, but simply it does not scroll anymore (I see whole content).
I'm speaking about including various content, not simply an image.

**Comment by wstoettinger** [comment] 2017-10-10 11:46
did you use the html markup? 

pd: i'm closing this now because the issue is already very old. in case you still have the problem. feel free to reopen.

**Closed by wstoettinger** 2017-10-10 11:46 UTC
