### ISSUE TITLE
White Space above the image

### ISSUE THREAD

**Issue by destefanis** [pixelcog/parallax.js#128] opened 2016-03-01 19:42 UTC
I've read a few similar bugs that have been marked close, but no matter what I do, there's always a gap above my image, likely from the math of the layout being off.

![screen shot 2016-03-01 at 1 40 22 pm](https://cloud.githubusercontent.com/assets/7717963/13439434/36741390-dfb3-11e5-9136-edb8752746b9.png)

I've attempted to use `$(window).trigger("resize").trigger("scroll");` and `$(window).trigger('resize.px.parallax');` using on Load callbacks for the `.parallax-slider` class and with other events to no success.

The gap corrects itself on page resize, but only then is it correct. Any ideas?

**Comment by damorossi** [comment] 2016-03-02 18:11
did you solve this?

**Comment by destefanis** [comment] 2016-03-03 17:11
No solution yet unfortunately. I also haven't had any time to troubleshoot this further, anyone else seeing this bug?

**Comment by alex100001** [comment] 2016-03-07 11:33
Has anyone gotten anywhere with this? I'm having a similar issue, I have a page with two parallaxs happening. The first one works fine, but with the second one, the image stops scrolling up about 40px before it should, causing it to be jammed right up against the div below (see image). Resizing the window completely fixes it, but attempts to trigger a resize event with js don't seem to work

![example](https://cloud.githubusercontent.com/assets/17701848/13568301/45efb88e-e458-11e5-8366-aef972d57af2.jpg)

I did accidentally manage to fix it by creating a conflict between two different versions of jQuery - I have an extremely limited knowledge of js and jQuery, so I have no idea why this would be the case - but the problem is that for me at least, this breaks something else on the page that's far more important...

**Comment by shonnamartell** [comment] 2016-03-08 16:24
I am having this same issue

**Comment by rogervila** [comment] 2016-03-14 10:23
I have the same issue.
The [demo page](http://pixelcog.github.io/parallax.js/) has the same issue too.

**Comment by ratze90** [comment] 2016-03-17 14:02
Think i'm having the same problem here. When i reload the page, sometimes it works without problems and the title will be displayed correct, sometimes not working correct.
![wrong](https://cloud.githubusercontent.com/assets/2630316/13848175/ea90499e-ec50-11e5-83ce-2b809cc539fd.png)
![correct](https://cloud.githubusercontent.com/assets/2630316/13848187/f252120c-ec50-11e5-8d65-a47591fc61ef.png)
![wrong_2](https://cloud.githubusercontent.com/assets/2630316/13848194/fca1c996-ec50-11e5-920d-34520388b234.png)
![correct_2](https://cloud.githubusercontent.com/assets/2630316/13848200/014ec28c-ec51-11e5-874d-2f2c960ac728.png)

Solution?

**Comment by MelchnerRoman** [comment] 2016-04-13 13:28
+1

**Comment by NatLuder** [comment] 2016-04-15 14:26
I have this issue when using Bootstrap 3 nav-fixed-top navigation which "jumps out" of the site.
Maybe it has to do with the window height not being the same anymore because of this effect?

**Comment by MelchnerRoman** [comment] 2016-04-15 14:29
@NatLuder i don´t use bootstrap and its happening to me too

**Comment by damorossi** [comment] 2016-04-15 15:00
I solved it by adding to body: padding-top: 0px; 
Don't know in your cases, but in mine it worked fine that way.

**Comment by NatLuder** [comment] 2016-04-18 08:22
I solved it with adding additional padding of the size of the navigation bar on top of the element which comes after the nav bar (which changes to nav-fixed-top when scrolling past the keyvisual) with jQuery.

So something like:
1) Keyvisual min-height: 600px;
2) Nav bar height: 50px;
3) Content element 'content-element'

on $('#keyvisual').outherHeight() scroll reached I am adding a padding class $('#content-element').addClass('pt50')
This gives me the padding which is missing from the jumped out nav bar.

Hope this kinda helps at least some of you guys.

**Comment by sashachirico** [comment] 2016-04-22 08:20
Agree, if i add padding-top: 0px its fix for me.

**Comment by damorossi** [comment] 2016-04-22 13:03
Glad to help

**Comment by Paleosun** [comment] 2016-04-28 17:10
The `padding-top: 0px;` doesn't work for me. So far, the only fix I can find is triggering a resize after things have loaded, like:
```
window.setTimeout(function(){
	$(window).resize();
},500);
```

**Comment by Paleosun** [comment] 2016-04-28 17:38
I actually found the source of my problem. I am also using a full width, responsive slider called LayerSlider, which is above my parallax sections. This slider area adjusts it's height as it loads, which was causing that gap at the top of my parallax element. To fix this, I waited to call parallax() until LayerSlider loaded completely, using the `cbInit` callback in LayerSlider. Hope this helps someone!

**Comment by PerryM123** [comment] 2016-05-12 00:51
I was having this issue as well.

In my case, I'm using bootstrap with parallax. Just like all of the above posters, I was running into the space issues after the user resizes the screen from 400px to 1200px or the other way around, which resulted in whitespace.

I believe (to my understanding), after resizing the window, parallax.js is calculating where everything is. Next bootstrap, rearranges everything which causes some whitespace.

My fix for this was:
-after the user resizes, wait a tiny bit of time to let bootstrap rearrange everything and then run resize() with jQuery to have parallax recalculate everything.

Hopefully this helps
`
var timer;
$(window).bind('resize', function() {
  clearTimeout(timer);
  timer = setTimeout(function(){ $(window).resize(); }, 250);
});`

**Comment by caseydev** [comment] 2016-09-08 11:17
#perryM123 
Thanks mate. It help for me too. I was also ruining on this since 2 days.

**Comment by VladLegkowski** [comment] 2016-11-07 13:37
Hi guys, total, **total** noob here, but I think there is a way round it in case if you used ` parallax.style.backgroundPositionY` in your `function`.

Add `if / else` to your `function myFunction ()` in `document.addEventListener("scroll", myFunction)`, and in your else statement set `...}else{parallax.style.backgroundPositionY= "0";}`

So if you don't scroll or come back to the top of the page your `background-position-y` is set to 0.

See this solution published online [By Abhishek Sachan](https://www.devstreak.com/parallax-scrolling-effect-with-pure-javascript/)

**Comment by damorossi** [comment] 2016-11-07 13:59
Solved with padding 0 to body

________________________________

**Comment by iamjosan** [comment] 2017-01-28 04:30
I am having this problem as well. I have two parallax elements on the same page. On both elements, the height is being calculated onLoad. The first element with the parallax works fine but on the second one, which is divided by another element that is at least 500px tall, the parallax image is being pushed down about 500px so there's a huge gap of whitespace.

I thought that the script that calculates the height of the elements was the problem so I removed it but the problem persisted. The weird part is that it corrects itself on window resize. 

I tried the **body{padding-top:0;}**  but that didn't help either. I am also using Bootstrap btw.

**Comment by raman15071991** [comment] 2017-02-20 05:20
#perryM123
Thanks your scripts is work for me now but still i am not able to solve this my own.

thanks again

**Comment by serdargulum** [comment] 2017-02-25 15:49
I have a simple solution : Just call parallax effect once, when your parallax element enters screen.

```
var parallax_tirggered = false;
$( window ).scroll(function() {
	if( !parallax_tirggered ){
		if($('.your_div').offset().top < $(window).scrollTop()+$(window).height()){ // Yur divs position
			parallax_effect();
			parallax_tirggered = true;
		}
	}
});

function parallax_effect(){
	$('.your_div').parallax();
});
```

**Comment by SeanPrashad** [comment] 2017-03-07 20:47
I have a similar issue in which I have a thin white horiontal line above one of my parallax elements. No fix has worked for me as yet. However if I remove height: 100%; from the main parallax (with an Id of #Intro), the line is gone however I want the main parallax background to be 100% width and height of the screen.

Line doesn't show up for Chrome but on Firefox it does.

Anyone know what I should look at next? My website in question is here: http://seanprashad.me/

**Comment by eberhardloh** [comment] 2017-09-17 11:58
we had the problem:
lazy-loaders trigger('resize.px.parallax') seemed not to be recognized (or too early?) by parallax.

thanks to serdargulum, i slightly modified it into this:
```
	var px_triggered = false;
	$(window).scroll(function () {
		if (!px_triggered) {
			if ($('.cestype-prllx').offset().top < $(window).scrollTop() + $(window).height()) {
				$(window).trigger('resize.px.parallax');
				px_triggered = true;
			}
		}
	});
```

**Comment by wstoettinger** [comment] 2017-10-10 12:06
seems to be solved for most users. 

summary:
- set body padding to 0
- add additional padding if you change your nav bar to fixed on scrolling
- create parallax (or trigger resize) after lazy loaders and or sliders/carousel are finished

**Closed by wstoettinger** 2017-10-10 12:06 UTC

**Comment by asonpatisson** [comment] 2019-08-14 16:46
Hi, guys!

I found a new solution to this problem. If you use parallax.js, it will be really helpful. You are right, the problem is in the plugin itself. JS adds to elements with class <code>.parallax-mirror</code> a css property <code>{overflow: hidden}</code>. I don’t understand why it's needed there, but ok. When I removed it from my code, everything became fine!
