### ISSUE TITLE
data-position-y is not working

### ISSUE THREAD

**Issue by chandru1822** [pixelcog/parallax.js#191] opened 2017-04-21 06:50 UTC
I tried to move the image towards down.data-position-y is not working.But data-position-x is working.please revert me with the solution as soon as possible.

**Comment by wstoettinger** [comment] 2017-10-10 08:16
this could be when the aspect ratio of the image is too high (meaning its width is larger than its height). The limit here is because the image needs to cover the window in each possible scrolling situation. Try reducing the parallax-window size or use an image with a different aspect ratio. In case I'm wrong, @mikegreiling knows this best!

**Comment by wstoettinger** [comment] 2017-10-10 11:22
duplicate of #158

**Closed by wstoettinger** 2017-10-10 11:22 UTC
