### ISSUE TITLE
Weird behavior in Firefox Quantum

### ISSUE THREAD

**Issue by alexstojda** [pixelcog/parallax.js#233] opened 2017-12-15 19:40 UTC
I have this weird behavior that I cant really describe well. if the top of a section below a parallax container scrolls off the page, then you scroll back to it, it appears to get "caught" by the top of the viewport before snapping back to its proper size. 

This is illustrated in the gif below, with the three frames containing the phenomenon elongated, pay attention to the space above the "Engineering & Computer Science..." text.

![Error Gif](https://i.imgur.com/PI1Uqsp.gif) 

Firefox Version: 57.0.2 (64-bit)

**Comment by SeanPrashad** [comment] 2017-12-17 03:05
I'm also receiving the same response on my personal website within Firefox Quantum (Version 57.0.1 - 64-bit).

Will need to try and rolling back to a previous version of FF to see if the bug still persists.

**Comment by humphd** [comment] 2017-12-17 17:44
I wonder if it's connected to this regression https://bugzilla.mozilla.org/show_bug.cgi?id=1424506

**Comment by SeanPrashad** [comment] 2017-12-30 22:27
@alexstojda - this behaviour should have been fixed with one of the latest updates to Firefox. Can you try to recreate it once more?

**Comment by alexstojda** [comment] 2017-12-31 02:43
@SeanPrashad its much less apparent, but if you have an eye for detail its still there every so slightly

**Comment by wstoettinger** [comment] 2018-02-21 08:59
since this seems to be an issue with Firefox Quantum rather than this library, i will close this issue

**Closed by wstoettinger** 2018-02-21 08:59 UTC
