### ISSUE TITLE
Parallax mirror wider than original image

### ISSUE THREAD

**Issue by McGern** [pixelcog/parallax.js#167] opened 2016-08-23 15:57 UTC
Hi,

Love the plugin, it worked straight out of the box. 

I have an issue though (probably my confusion) about how to correctly set what part of the image is in view. I am using a container that maintains a constant ratio and have made my image height larger than the container height hoping that the image would cover the width and overflow on the height. 

What I am seeing is that the mirror image width is always bigger than the container width and this varies based the on the width of the container; the larger the container the closer it it gets to fitting the container. For a small container size, the image is right off the edges. It seems to maintain the overall view size of the image, no matter what width the container is. 

I have tried faking the naturalWidth and naturalHeight settings to represent a fake size of the image based on the container ratio, but it doesn't seem to change anything.

Is there some configuration I need to set?

Thanks,
Jarrod

**Comment by wstoettinger** [comment] 2017-10-10 09:32
The height is chosen, so that the image covers the container at all times in all scroll positions. If you don't want the image to overlap left and right, the image needs to be tall enough to cove the container in all scroll positions. 

hope this helps! 

pd: i'm closing this now because the issue is already very old. in case you still have the problem. feel free to reopen.

**Closed by wstoettinger** 2017-10-10 09:32 UTC
