### ISSUE TITLE
massiv jittering with FF 57 & 58

### ISSUE THREAD

**Issue by Marcelwalter** [pixelcog/parallax.js#244] opened 2018-02-02 11:32 UTC
The parallax scrolling effect works really well in chrome and safari. But i just checked my website in FF and seems so laggy, that i'm considering to remove the effekt from FF via the iosFIX.

Maybe it just looks so bad, because of my "backup parallax". I added another div inside the parallax with the same background image (basicly to not scrolling parallax version) as fallback if JS can't be used.

Is it a common problem with FF, or is it just my code?

**Comment by Leafy3311** [comment] 2018-02-11 00:50
I've been having the same jittering on FF for Mac ever since the Quantum upgrade. It was working great before Quantum and works well in other modern browsers but now it's jittering.

**Comment by wstoettinger** [comment] 2018-02-21 08:26
duplicate of #233

**Closed by wstoettinger** 2018-02-21 08:26 UTC
