### ISSUE TITLE
parallax-mirror not updated

### ISSUE THREAD

**Issue by ziiCz** [pixelcog/parallax.js#151] opened 2016-05-22 09:20 UTC
Hi guy,

I followed the installation steps but my div element will not turn up to date when I scroll.

No errors detected in the console.

My div .parralax-mirror is created quite the page loads but no update is performed.

Thank you,

Best Regards,

**Comment by wstoettinger** [comment] 2017-10-10 11:38
hey @ziiCz! are you still having this issue with the latest version? 

pd: i'm closing this now because the issue is already very old. in case you still have the problem. feel free to reopen.

**Closed by wstoettinger** 2017-10-10 11:38 UTC
