### ISSUE TITLE
Conflict with Boostrap's carousel feature

### ISSUE THREAD

**Issue by markmadedesign** [pixelcog/parallax.js#116] opened 2016-01-28 16:07 UTC
Greetings! I enjoy this parallax feature you've created but I'm having an issue when it's towards the bottom of the page and near another section that has collapsed content. The parallax background anchors itself while content scrolls over top of it.

http://henderson.consociate.marketing/about-us/safety/

Scroll down to the bottom and click the blue Sitemap button, then notice the funky as you scroll down a little more after that. Any thoughts as to why this happening? Thanks for any assistance!

**Comment by wstoettinger** [comment] 2016-01-28 16:54
you could try to trigger a resize when the sitemap button is pressed.
```javascript
$(window).trigger('resize.px.parallax');
```

**Comment by markmadedesign** [comment] 2016-04-06 20:35
Good afternoon! I still haven't had a chance to try the resize trigger you mentioned for this specific issue but I noticed something else with the parallax, happening only in Chrome browser.

On a certain page on my client's site, when it initially loads the content above a parallax instance is overflowing into the parallax area. When I slightly resize the browser after seeing the issue, everything snaps back into place (no more overflow) like it should look. I've attached a screenshot and the link. Any ideas? This doesn't happen in Safari or Firefox from what I can tell.

http://hendersoninc.com/portfolio/busch-gardens/

Thanks in advance!

![screen shot 2016-04-06 at 4 33 57 pm](https://cloud.githubusercontent.com/assets/11360418/14331970/7982b456-fc15-11e5-89c9-3ac809bf4299.png)

**Comment by wstoettinger** [comment] 2017-10-10 13:55
@markmadedesign you second issue (although I couldn't replicate it) seems to me like a problem of the div above. Could you solve it already? 

concerning your first issue, you could also have a look at #88

pd: i'm closing this now because the issue is already very old. in case you still have the problem. feel free to reopen.

**Closed by wstoettinger** 2017-10-10 13:55 UTC
