### ISSUE TITLE
Use Parallax.js with json

### ISSUE THREAD

**Issue by lfractucello** [pixelcog/parallax.js#129] opened 2016-03-02 18:11 UTC
How do I apply the elements via json , if I try to give append them by json with date atributes it does not render .

The page stay blank, the images not show.

I use getjson and append with jquery

<div class="parallax-window" data-parallax="scroll" data-image-src="/path/to/image.jpg"></div>

**Comment by wstoettinger** [comment] 2017-10-10 14:07
I don't completely comprehend what you are trying to achieve. Am I correct, that you are creating a DOM Element from json with jQuery and you would like to initialize the parallax effect on it? In order to do that, you would need to call the initialization on the element after you created it via `$('.parallax-window').parallax();` (where your new element needs to have the class .parallax-window).

pd: i'm closing this now because the issue is already very old. in case you still have the problem. feel free to reopen.

**Closed by wstoettinger** 2017-10-10 14:07 UTC
